//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoCover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public string order_id { get; set; }
        public Nullable<int> user_create_id { get; set; }
        public Nullable<int> user_finish_id { get; set; }
        public Nullable<int> order_status { get; set; }
        public Nullable<decimal> order_price { get; set; }
        public string order_type { get; set; }
        public string order_title { get; set; }
        public string order_content { get; set; }
        public Nullable<int> order_specifiedtime { get; set; }
        public Nullable<System.DateTime> order_create_time { get; set; }
        public Nullable<System.DateTime> order_finish_time { get; set; }
        public string order_cust_email { get; set; }
        public string order_picture { get; set; }
        public string order_remark { get; set; }
        public string order_penname { get; set; }
    
        public virtual Users User_Create { get; set; }
        public virtual Users Users_Finish { get; set; }
    }
}
