//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoCover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        public int rank_num { get; set; }
        public string rank_name { get; set; }
        public Nullable<int> rank_condition { get; set; }
        public Nullable<decimal> rank_price { get; set; }
    }
}
