//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoCover.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Orders_Create = new HashSet<Orders>();
            this.Orders_Finish = new HashSet<Orders>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_pwd { get; set; }
        public Nullable<int> user_type { get; set; }
        public string user_nick_name { get; set; }
        public string user_qq { get; set; }
        public string user_email { get; set; }
        public string user_phone { get; set; }
        public Nullable<bool> user_status { get; set; }
        public string user_portrait { get; set; }
        public Nullable<System.DateTime> user_reg_time { get; set; }
        public string user_reg_ip { get; set; }
        public Nullable<System.DateTime> user_last_login_time { get; set; }
        public string user_last_login_ip { get; set; }
        public Nullable<System.DateTime> user_last_update_time { get; set; }
        public string user_last_update_ip { get; set; }
        public Nullable<int> user_login_num { get; set; }
        public Nullable<decimal> user_money { get; set; }
        public Nullable<int> user_rankscores { get; set; }
        public string user_random { get; set; }
        public string user_remark { get; set; }
        public Nullable<int> user_extend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders_Create { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders_Finish { get; set; }
    }
}
